### ISSUE TITLE
Dropbox daemon doesn't work

### ISSUE THREAD

**Issue by csu** [sagemath/cloud#172]
I'm trying to follow the instructions from: http://ask.sagemath.org/question/10713/is-there-a-way-to-store-and-sync-the-files-from-sage-cloud-on-local-hard-drive/

Here is what I am getting:
    ~$ dropbox start -i
    Starting Dropbox...
    Dropbox is the easiest way to share and store your files online. Want to learn more? Head to https://www.dropbox.com/

```
In order to use Dropbox, you must download the proprietary daemon. [y/n] y

Error: Trouble connecting to Dropbox servers. Maybe your internet connection is down, or you need to set your http_proxy environment variable.
Traceback (most recent call last):
  File "/usr/bin/dropbox", line 1257, in start
    download()
  File "/usr/bin/dropbox", line 558, in download
    FatalVisibleError(ERROR_CONNECTING)
  File "/usr/bin/dropbox", line 517, in FatalVisibleError
    sys.exit(-1)
SystemExit: -1
~$  
```

**Comment by antonbabkin** [comment]
Was trying to do same thing: install Dropbox daemon in my project. Same problem, can't connect to Dropbox servers.

Project Settings -> Project usage and quotas -> External network access: false

Can't find a way to change this setting. Does external access require a "members-only machine"? Meaning that it's impossible to use Dropbox without subscription?

**Comment by williamstein** [comment]
It seems impossible to use dropbox from SMC with our without external network access.  Dropbox linking is not available in any way yet.   I would change the askbot answer, but I can't use askbot anymore due to openid  being deprecated, so I can't access my account (and a new account I just made doesn't have any karma).

**Comment by antonbabkin** [comment]
Thanks for the quick response! Will be great to see some form of local hard drive synchronization eventually.

**Comment by williamstein** [comment]
On Sun, Jun 7, 2015 at 9:44 PM, Anton Babkin <notifications@github.com>
wrote:

> Thanks for the quick response! Will be great to see some form of local
> hard drive synchronization eventually.
>

I should point out that two weeks ago Chris Swenson heroically implemented
dropbox sync for SMC:


https://github.com/sagemathinc/smc/blob/master/salvus/dropbox_syncer.coffee

We haven't enabled it yet due to some serious security concerns that need
to carefully be thought through, and some integration with the other
daemons.  But it's not just some distant hope!




> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sagemath/cloud/issues/172#issuecomment-109861046>.
>



-- 
William (http://wstein.org)

**Comment by williamstein** [comment]
See https://github.com/sagemathinc/smc/issues/11
